package cn.tiger.entity.bbs;
// Generated 2016-6-3 15:51:46 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CheckTopicAd generated by hbm2java
 * 不使用Hibernate关联查询 简化关联配置 查询使用HQL
 */
@Entity
@Table(name = "check_topic_ad")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class CheckTopicAd implements java.io.Serializable {

	private Long id;
	private long userId;
	private long topicId;

	public CheckTopicAd() {
	}

	public CheckTopicAd(long userId, long topicId) {
		this.userId = userId;
		this.topicId = topicId;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name="user_id")
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name="topic_id")
	public long getTopicId() {
		return this.topicId;
	}

	public void setTopicId(long topicId) {
		this.topicId = topicId;
	}

}
