package cn.tiger.entity.bbs;
// Generated 2016-6-4 23:16:12 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CheckCommentAd generated by hbm2java
 */
@Entity
@Table(name = "check_comment_ad")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class CheckCommentAd implements java.io.Serializable {

	private Long id;
	private long userId;
	private long commentId;

	public CheckCommentAd() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name="user_id")
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name="comment_id")
	public long getCommentId() {
		return this.commentId;
	}

	public void setCommentId(long commentId) {
		this.commentId = commentId;
	}

}
