package cn.tiger.entity.bbs;
// Generated 2016-6-4 23:16:12 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * CommentAd generated by hbm2java
 */
@Entity
@Table(name = "comment_ad")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class CommentAd implements java.io.Serializable {

	private Long id;
	private long agreeCount;
	private long dsagreeCount;
	
	private Comment comment;

	public CommentAd() {
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name="agree_count")
	public long getAgreeCount() {
		return this.agreeCount;
	}

	public void setAgreeCount(long agreeCount) {
		this.agreeCount = agreeCount;
	}

	@Column(name="dsagree_count")
	public long getDsagreeCount() {
		return this.dsagreeCount;
	}

	public void setDsagreeCount(long dsagreeCount) {
		this.dsagreeCount = dsagreeCount;
	}
	
	@OneToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="comment_id")
	public Comment getComment() {
		return comment;
	}

	public void setComment(Comment comment) {
		this.comment = comment;
	}

}
